[package]
name = "my_bevy_game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.2", path = ".." }

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

[workspace]

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3


